name: expense
networks:
  default:
    external: true
    name: expense
volumes:
  mysql: # docker volume create mysql
services:
  mysql:
    image: aravind19981999/mysql-db:v1.0
    container_name: mysql # --name mysql
    volumes:
      - source: mysql
        target: /var/lib/mysql # mount point in the container
        type: volume # -v volume-name:/path/in/container
  backend:
    image: aravind19981999/expense-backend:v1.0
    container_name: backend # --name backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on:
      - mysql
  frontend:
    image: aravind19981999/expense-frontend:v1.0
    container_name: frontend # --name frontend
    depends_on:
      - backend
    ports: # expose port 80 of the container to host
      - "80:80"