name: expense
networks:
  default:
    name: expense
services:
  mysql:
    image: mysql-db:v1.0
    container_name: mysql # --name mysql
  backend:
    image: expense-backend:v1.0
    container_name: backend # --name backend
    depends_on:
      - mysql
  frontend:
    image: expense-frontend:v1.0
    container_name: frontend # --name frontend
    depends_on:
      - backend
    ports: # expose port 80 of the container to host
      - "80:80"